FROM python:3.7
ENV PYTHONUNBUFFERED 1

RUN pip3.7 install pipenv

COPY . code
WORKDIR /code
RUN pipenv install --system --dev

EXPOSE 8000

CMD cd backend && python manage.py migrate && daphne -b 0.0.0.0 -p 8000 backend.asgi:application
