# Generated by Django 2.1.5 on 2019-01-20 16:59

from django.db import migrations, models
import movies.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('year', models.CharField(default=None, max_length=4)),
                ('description', models.TextField(default=None, null=True)),
                ('url', models.URLField(null=True)),
            ],
            managers=[
                ('objects', movies.managers.MovieManager()),
            ],
        ),
    ]
